spring:
  application:
    name: spring-boot-demo
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springmvc?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8
    username: root
    password: rootroot
    druid:
      # ????????
      initial-size: 5  # ????????
      max-active: 30  # ?????
      min-idle: 5   # ?????

      # ?????????????
      max-wait: 60000  #???????????????1min=60000ms
      validation-query: SELECT 1 FROM DUAL  #??????????????????????????????????
      # ??????????????????????
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      # ??SQL?????????????
      filters: stat,wall,slf4j
      # ??DruidStatViewServlet
      stat-view-servlet:
        # ???
        login-username: admin
        # ????
        login-password: admin
        url-pattern: /druid/*
        # IP???(????????????????)
        allow: 192.167.10.1,127.0.0.1  # ??????ip??????????
        reset-enable: false # ????
        # ?????-???????????????????404
        enabled: true
#  ??freemarker???
#  freemarker:
#    template-loader-path: classpath:/views/
#  main:
#    banner-mode: off
mybatis:
  type-aliases-package: org.example.springbootdemo.pojo
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    org.example.springbootdemo.mapper: trace
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true